-- Mission Pool Supabase schema and row-level security baseline.
create extension if not exists "pgcrypto";
create table profiles (id uuid primary key references auth.users on delete cascade, username text unique not null, name text not null, bio text default '', avatar_url text, created_at timestamptz default now());
create table pools (id uuid primary key default gen_random_uuid(), steward_id uuid references profiles not null, slug text unique not null, title text not null, summary text not null, category text not null, location text, visibility text default 'public', cover_url text, rules text, created_at timestamptz default now());
create table pool_members (pool_id uuid references pools on delete cascade, user_id uuid references profiles on delete cascade, role text default 'member', created_at timestamptz default now(), primary key(pool_id,user_id));
create table moderators (pool_id uuid references pools on delete cascade, user_id uuid references profiles on delete cascade, primary key(pool_id,user_id));
create table posts (id uuid primary key default gen_random_uuid(), pool_id uuid references pools on delete cascade, author_id uuid references profiles, body text not null, created_at timestamptz default now());
create table comments (id uuid primary key default gen_random_uuid(), post_id uuid references posts on delete cascade, author_id uuid references profiles, body text not null, created_at timestamptz default now());
create table mission_updates (id uuid primary key default gen_random_uuid(), pool_id uuid references pools on delete cascade, author_id uuid references profiles, title text not null, body text not null, created_at timestamptz default now());
create table outcomes (id uuid primary key default gen_random_uuid(), pool_id uuid references pools on delete cascade, submitter_id uuid references profiles, title text not null, description text not null, status text default 'pending', created_at timestamptz default now());
create table outcome_members (outcome_id uuid references outcomes on delete cascade, user_id uuid references profiles on delete cascade, primary key(outcome_id,user_id));
create table conversations (id uuid primary key default gen_random_uuid(), created_at timestamptz default now());
create table conversation_members (conversation_id uuid references conversations on delete cascade, user_id uuid references profiles on delete cascade, primary key(conversation_id,user_id));
create table messages (id uuid primary key default gen_random_uuid(), conversation_id uuid references conversations on delete cascade, sender_id uuid references profiles, body text not null, created_at timestamptz default now());
create table access_requests (id uuid primary key default gen_random_uuid(), pool_id uuid references pools on delete cascade, user_id uuid references profiles on delete cascade, status text default 'pending', unique(pool_id,user_id));
alter table profiles enable row level security; alter table pools enable row level security; alter table pool_members enable row level security; alter table posts enable row level security; alter table comments enable row level security; alter table mission_updates enable row level security; alter table outcomes enable row level security; alter table conversations enable row level security; alter table conversation_members enable row level security; alter table messages enable row level security;
create policy "profiles public read" on profiles for select using (true);
create policy "profiles owner update" on profiles for update using (auth.uid()=id);
create policy "public pools readable" on pools for select using (visibility='public' or steward_id=auth.uid() or exists(select 1 from pool_members where pool_id=pools.id and user_id=auth.uid()));
create policy "authenticated create pools" on pools for insert with check (auth.uid()=steward_id);
create policy "steward update pools" on pools for update using (auth.uid()=steward_id);
create policy "members readable" on pool_members for select using (true);
create policy "self join" on pool_members for insert with check (auth.uid()=user_id);
create policy "self leave except steward" on pool_members for delete using (auth.uid()=user_id and not exists(select 1 from pools where id=pool_id and steward_id=auth.uid()));
create policy "members read posts" on posts for select using (exists(select 1 from pools p where p.id=pool_id and (p.visibility='public' or exists(select 1 from pool_members m where m.pool_id=p.id and m.user_id=auth.uid()))));
create policy "members create posts" on posts for insert with check (auth.uid()=author_id and exists(select 1 from pool_members where pool_id=posts.pool_id and user_id=auth.uid()));
create policy "authorized delete posts" on posts for delete using (auth.uid()=author_id or exists(select 1 from pools where id=pool_id and steward_id=auth.uid()) or exists(select 1 from moderators where pool_id=posts.pool_id and user_id=auth.uid()));
create policy "members create comments" on comments for insert with check (auth.uid()=author_id and exists(select 1 from posts join pool_members on pool_members.pool_id=posts.pool_id where posts.id=post_id and pool_members.user_id=auth.uid()));
create policy "official updates read" on mission_updates for select using (true);
create policy "official updates write" on mission_updates for insert with check (auth.uid()=author_id and (exists(select 1 from pools where id=pool_id and steward_id=auth.uid()) or exists(select 1 from moderators where pool_id=mission_updates.pool_id and user_id=auth.uid())));
create policy "outcomes public approved" on outcomes for select using (status='approved' or submitter_id=auth.uid() or exists(select 1 from pools where id=pool_id and steward_id=auth.uid()));
create policy "members submit outcomes" on outcomes for insert with check (auth.uid()=submitter_id and exists(select 1 from pool_members where pool_id=outcomes.pool_id and user_id=auth.uid()));
create policy "conversation members read" on conversations for select using (exists(select 1 from conversation_members where conversation_id=conversations.id and user_id=auth.uid()));
create policy "own conversation membership" on conversation_members for select using (user_id=auth.uid());
create policy "conversation messages read" on messages for select using (exists(select 1 from conversation_members where conversation_id=messages.conversation_id and user_id=auth.uid()));
create policy "conversation messages send" on messages for insert with check (auth.uid()=sender_id and exists(select 1 from conversation_members where conversation_id=messages.conversation_id and user_id=auth.uid()));
